namespace Entities
{
    public class cq_deluser
    {
		public int? id { get; set; }
		public string name { get; set; }
		public string mate { get; set; }
		public int? mate_id { get; set; }
		public int? lookface { get; set; }
		public int? hair { get; set; }
		public int? money { get; set; }
		public int? money_saved { get; set; }
		public int? RMB { get; set; }
		public int? level { get; set; }
		public long? exp { get; set; }
		public int? storage_lv { get; set; }
		public int? deed { get; set; }
		public int? pk { get; set; }
		public int? medal { get; set; }
		public int? storage_stone_limit { get; set; }
		public int? CreateTime { get; set; }
		public int? recordmap_id { get; set; }
		public int? recordx { get; set; }
		public int? recordy { get; set; }
		public int? account_id { get; set; }
		public int? last_login { get; set; }
		public int? task_mask { get; set; }
		public int? home_id { get; set; }
		public int? title { get; set; }
		public int? storage_weight_limit { get; set; }
		public int? lock_key { get; set; }
		public int? reborn_mapid { get; set; }
		public int? newtype_lv { get; set; }
		public int? Coach { get; set; }
		public int? Coach_time { get; set; }
		public int? Coach_date { get; set; }
		public int? virtue { get; set; }
		public int? xp_beat { get; set; }
		public int? camp { get; set; }
		public int? pkenable { get; set; }
		public int? militaryrank1 { get; set; }
		public int? militaryrank2 { get; set; }
		public int? militaryrank3 { get; set; }
		public int? militaryrank4 { get; set; }
		public int? marrytime { get; set; }
		public int? robotstorage_lev { get; set; }
		public int? accumulate { get; set; }
		public int? Emoney { get; set; }
		public int? Emoney_chk { get; set; }
		public int? money_saved2 { get; set; }
		public int? ExpBallUsage { get; set; }
		public int? status { get; set; }
		public int? stratagem { get; set; }
		public int? online_time { get; set; }
		public int? auto_exercise { get; set; }
		public int? flower { get; set; }
		public int? BagNum { get; set; }
		public int? forbitdden_words { get; set; }
		public int? CrystalPoint { get; set; }
		public int? CrystalUsage0 { get; set; }
		public int? CrystalUsage1 { get; set; }
		public int? CrystalUsage2 { get; set; }
		public int? CrystalUsage3 { get; set; }
		public int? CrystalUsage4 { get; set; }
		public int? password_id { get; set; }
		public int? locktime { get; set; }
		public int? chk_sum { get; set; }
		public int? flower_w { get; set; }
		public int? tutor_level { get; set; }
		public long? Tutor_exp { get; set; }
		public int? online_time2 { get; set; }
		public int? offine_time { get; set; }
		public int? last_logout2 { get; set; }
		public int? list1 { get; set; }
		public int? list2 { get; set; }
		public long? friend_share { get; set; }
		public int? Battle_lev { get; set; }
		public long? Income { get; set; }
		public int? business { get; set; }
		public int? airborne { get; set; }
		public int? emoney2 { get; set; }
		public int? Emoney3 { get; set; }
		public int? Emoney3_chk { get; set; }
		public long? donation { get; set; }
		public int? login_time { get; set; }
		public string ip { get; set; }
		public int? brother_team_id { get; set; }

    }
}
