namespace Entities
{
    public class cq_monstertype
    {
		public int? id { get; set; }
		public string name { get; set; }
		public int? sort { get; set; }
		public int? lookface { get; set; }
		public int? life { get; set; }
		public int? mana { get; set; }
		public int? dexterity { get; set; }
		public int? dodge { get; set; }
		public int? helmet_type { get; set; }
		public int? armor_type { get; set; }
		public int? weaponr_type { get; set; }
		public int? weaponl_type { get; set; }
		public int? attack_range { get; set; }
		public int? view_range { get; set; }
		public int? escape_life { get; set; }
		public int? attack_speed { get; set; }
		public int? move_speed { get; set; }
		public int? level { get; set; }
		public int? attack_user { get; set; }
		public int? drop_money_min { get; set; }
		public int? drop_money_max { get; set; }
		public int? size_add2 { get; set; }
		public int? action { get; set; }
		public int? run_speed { get; set; }
		public int? hot_power { get; set; }
		public int? cold_power { get; set; }
		public int? shake_power { get; set; }
		public int? drop_ring { get; set; }
		public int? drop_weapon { get; set; }
		public int? drop_shield { get; set; }
		public int? drop_shoes { get; set; }
		public int? drop_money_change { get; set; }
		public int? drop_item_change { get; set; }
		public int? magic_type { get; set; }
		public int? magic_def { get; set; }
		public int? magic_hitrate { get; set; }
		public int? ai_type { get; set; }
		public int? explode_change1 { get; set; }
		public int? explode_change2 { get; set; }
		public int? explode_change3 { get; set; }
		public int? drop_item_rule { get; set; }
		public int? atk_max { get; set; }
		public int? atk_min { get; set; }
		public int? atk_hot { get; set; }
		public int? atk_shake { get; set; }
		public int? atk_ice { get; set; }
		public int? atk_decay { get; set; }
		public int? def_adj { get; set; }
		public int? def_sub { get; set; }
		public int? def_hot { get; set; }
		public int? def_shake { get; set; }
		public int? def_sting { get; set; }
		public int? def_decay { get; set; }
		public int? weapon_amount { get; set; }
		public int? armor_amount { get; set; }
		public int? thruster_amount { get; set; }
		public int? d_stealitem { get; set; }
		public int? award_exp { get; set; }
		public int? drop_stone_change { get; set; }
		public int? drop_stone_min { get; set; }
		public int? drop_stone_max { get; set; }
		public int? magic_type1 { get; set; }
		public int? magic_type2 { get; set; }
		public int? magic_type3 { get; set; }
		public int? magic_assistan { get; set; }
		public int? magic_assistan2 { get; set; }
		public int? magic_passive { get; set; }
		public int? magic_passive2 { get; set; }
		public int? status_def { get; set; }
		public int? status_lv { get; set; }
		public int? somatotype { get; set; }
		public int? camp { get; set; }
		public int? drop_equip_coe { get; set; }
		public int? drop_ammo_coe { get; set; }
		public int? drop_part_coe { get; set; }
		public int? drop_amplifier_coe { get; set; }
		public int? drop_HumanItem_coe { get; set; }
		public int? drop_expendable_coe { get; set; }
		public int? drop_InsideItem_coe { get; set; }
		public int? drop_explode_coe { get; set; }
		public int? drop_Special_coe { get; set; }
		public int? special_type { get; set; }
		public int? drop_deltalev_coe { get; set; }
		public int? attribute_type { get; set; }
		public int? extra_battlelev { get; set; }
		public int? extra_exp { get; set; }
		public int? extra_damage { get; set; }
		public int? drop_stone_type { get; set; }
		public int? User_atk_adjust { get; set; }
		public int? exempt_damage { get; set; }
		public int? pertinence_magic { get; set; }
		public int? pertinence_magic_damage { get; set; }
		public int? pertinence_weapon { get; set; }
		public int? pertinence_weapon_damage { get; set; }
		public int? drop_emoney_coe { get; set; }
		public int? drop_other_coe { get; set; }
		public int? price { get; set; }
		public int? user_atk_mode { get; set; }
		public int? pertinence_transfrom { get; set; }
		public int? pertinence_transfrom_damage { get; set; }
		public int? weakness_tips { get; set; }

    }
}
